<a href="https://colab.research.google.com/github/ivanbergon/Ivan_Portfolio/blob/main/Recommendation%20System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sistema de recomendação
____

Autor: Ivan Berlim Gonçalves

*atualizado em 10/08/2021*

## Objetivos:

### .Ler dados existentes e armazena-los em um dataframe
1. `songs-spotify.csv`: esse arquivo contém músicas de diferentes playlists do Spotify, com seus gêneros e respectivos artistas.
2. `user-ratings.csv`: esse arquivo contém a avaliação de cada usuário fictício para as músicas das playlists mostradas no arquivo anterior. 

### .Criar e aplicar uma função que gere notas aleatórias

### .Gerar um dataframe de acordo com as seguintes regras:
* O intervalo de notas possível para dar a uma música esteja entre 1 e 3
* Para simular o fato de que nem todos os usuários avaliam as músicas, ajustar a função `create_user_ratings` para que 23% das avaliações sejam `NaN`

### .Moldar o dataframe para a estrutura desejada (cada linha representa um usuário e cada coluna representa cada música que pode ter sido avaliada ou não)

### .Montar três cenários de recomendações:

1. Cenário 01: montar um mini sistema de recomendação com os requisitos abaixo:

  1.1. Preencher os valores faltantes com zero

  1.2. Aplicar a mesma função de ajuste de nota vista em aula

  1.3. Utilizar a distância eucliana para medir similaridade. (_Dica: use a função `euclidian_distances()` do Scikit Learn_)

  1.4. Não aplicar a variável `penalizer` durante as recomendações

  1.5. Retornando as top 5 recomendações de músicas, ordenadas da música mais similar para a menos similar.

2. Cenário 02: montar um mini sistema de recomendação com os requisitos abaixo:

  2.1. Preencher os valores faltantes com nota máxima

  2.2. Aplicar a mesma função de ajuste de nota vista em aula

  2.3. Utilizar a distância eucliana para medir similaridade. (_Dica: use a função `euclidian_distances()` do Scikit Learn_)

  2.4. Não aplica a variável `penalizer` durante as recomendações

  2.5. Retornando as top 5 recomendações de músicas, ordenadas da música mais similar para a menos similar.


3. Cenário 03: montar um mini sistema de recomendação com os requisitos abaixo:

  3.1. Preencher os valores faltantes com zero

  3.2. Usar uma função de ajuste de nota que, ao invés de subtrair a média das linhas de cada nota dada por um usuário, usa a mediana. 

  3.3. Utilizar a similaridade do cosseno

  3.4. Não aplicar a variável `penalizer` durante as recomendações

  3.5. Retornando as top 5 recomendações de músicas, ordenadas da música mais similar para a menos similar.

# .Ler dados existentes e armazena-los em um dataframe

In [ ]:
import pandas as pd           # importa biblioteca Pandas e a chama de 'pd'
import sklearn                # importa biblioteca Sklearn
import random                 # importa biblioteca Random
import numpy as np            # importa biblioteca Numpy e a chama de 'np'

## 1. `songs-spotify.csv`: esse arquivo contém músicas de diferentes playlists do Spotify, com seus gêneros e respectivos artistas.

In [ ]:
df_songs_path = "/content/drive/MyDrive/Data science/Curso Awari - Data Science/Atividade 2/songs-spotify-backup.csv"       # o caminho do arquivo de dados .csv foi relacionado à variável df_songs_path
df_songs = pd.read_csv(df_songs_path)                                                                                       # o dataset foi armazenado como df_songs através da função da biblioteca pandas pd.read_csv(caminho)
df_songs_backup = "/content/drive/MyDrive/Data science/Curso Awari - Data Science/Atividade 2/songs-spotify-backup2.csv"    # foi criado um backup chamado de df_songs_backup
df_songs.to_csv(df_songs_backup)                                                                                            # os dados foram efetivamente copiados de df_songs para df_song_backup através da função .to_csv(variável)
df_songs.info()                                                                                                             # informações básicas sobre o arquivo df_songs
print("_______________________________")
df_songs.head()                                                                                                             # 5 primeiros cabeçalhos de df_songs

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Unnamed: 0      229 non-null    int64 
 1   Unnamed: 0.1    229 non-null    int64 
 2   id              229 non-null    int64 
 3   playlist_name   229 non-null    object
 4   playlist_genre  229 non-null    object
 5   artists         229 non-null    object
 6   name            229 non-null    object
dtypes: int64(3), object(4)
memory usage: 12.6+ KB
_______________________________


Unnamed: 0  ...                                               name
0           0  ...                     love race (feat. Kellin Quinn)
1           1  ...                 WANNA BE (feat. Machine Gun Kelly)
2           2  ...                                    A Girl Like You
3           3  ...                          DAYWALKER! (feat. CORPSE)
4           4  ...  PILL BREAKER (feat. blackbear & Machine Gun Ke...

[5 rows x 7 columns]

## 2. `user-ratings.csv`: esse arquivo contém a avaliação de cada usuário fictício para as músicas das playlists mostradas no arquivo anterior. 

In [ ]:
df_user_ratings_path = "/content/drive/MyDrive/Data science/Curso Awari - Data Science/Atividade 2/user-ratings-backup.csv"     # o caminho do arquivo de dados .csv foi relacionado à variável df_user_ratings_path
df_user_ratings = pd.read_csv(df_user_ratings_path)                                                                             # o dataset foi armazenado como df_user_ratings através da função da biblioteca pandas pd.read_csv(caminho)
df_user_ratings_backup = "/content/drive/MyDrive/Data science/Curso Awari - Data Science/Atividade 2/user-ratings-backup2.csv"  # foi criado um backup chamado de df_user_ratings_backup
df_user_ratings.to_csv(df_user_ratings_backup)                                                                                  # os dados foram efetivamente copiados de df_songs para df_song_backup através da função .to_csv(variável)
df_user_ratings.info()                                                                                                          # informações básicas sobre o arquivo df_songs
print("-------------")
df_user_ratings.head()                                                                                                          # 5 primeiros cabeçalhos de df_songs

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11450 entries, 0 to 11449
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    11450 non-null  int64  
 1   Unnamed: 0.1  11450 non-null  int64  
 2   track_id      11450 non-null  int64  
 3   name          11450 non-null  object 
 4   user_id       11450 non-null  int64  
 5   rating        9417 non-null   float64
dtypes: float64(1), int64(4), object(1)
memory usage: 536.8+ KB
-------------


Unnamed: 0  Unnamed: 0.1  ...  user_id rating
0           0             0  ...        1    1.0
1           1             1  ...        1    4.0
2           2             2  ...        1    NaN
3           3             3  ...        1    3.0
4           4             4  ...        1    3.0

[5 rows x 6 columns]

# .Criação e aplicação de uma função que gere notas aleatórias

In [ ]:
# função para gerar códigos pseudo-aleatórios
def get_context_random_int(row, genre_lover, a, b):
  if genre_lover != None and row["playlist_genre"] == genre_lover:
    return random.randint(round((a+b)/2,0) + 1, b)

  return(random.randint(a, b))

# função para gerar notas pseudo-aleatórias com intervalo de valor definido (no caso, de 1 a 3)
def generate_ratings(df_songs, user_id, genre_lover=None, min_rating=1, max_rating=3):
  df_songs["user_id"] = user_id
  df_songs["rating"] = df_songs.apply(lambda row: get_context_random_int(row, genre_lover, min_rating, max_rating), axis=1)
  return(df_songs.drop(["playlist_name", "playlist_genre", "artists"], axis=1))

# Função para criar as notas pseudo-aleatórias, com porcentagem de valores nulos
def create_user_ratings(users_count, percentage_of_missing_values):

  dfs = []
  for i in range(users_count):
    if i > 10 and i < 30:
      genre_lover = "punk-rock"
    elif i >= 30 and i < 60:
      genre_lover = "soul-funk"
    elif i >= 60 and i < 95:
      genre_lover = "arrocha"
    else:
      genre_lover = None
  
    dfs.append(generate_ratings(df_songs.copy(), i+1, genre_lover=genre_lover))

  df_ratings = pd.concat(dfs).rename(columns={"id": "track_id"})

  # adiciona NaN aleatoriamente na coluna de rating de acordo com um percentual de corte no dataframe
  df_ratings["rating"] = df_ratings["rating"].mask(np.random.random(df_ratings.shape[0]) < percentage_of_missing_values)

  return df_ratings

# .Gerar um novo dataframe de acordo com as seguintes regras:
* O intervalo de notas possível para dar a uma música esteja entre 1 e 3
* Para simular o fato de que nem todos os usuários avaliam as músicas, ajustar a função `create_user_ratings` para que 23% das avaliações sejam `NaN`

In [ ]:
df_user_ratings2 = create_user_ratings(50,0.23)   # criação do novo data frame chamado df_user_ratings2, com 50 usuários e 23% de avaliações nulas
df_user_ratings2.head()

Unnamed: 0  Unnamed: 0.1  ...  user_id rating
0           0             0  ...        1    NaN
1           1             1  ...        1    3.0
2           2             2  ...        1    1.0
3           3             3  ...        1    1.0
4           4             4  ...        1    NaN

[5 rows x 6 columns]

# .Moldar o dataframe para a estrutura desejada (cada linha representa um usuário e cada coluna representa cada música que pode ter sido avaliada ou não)

In [ ]:
# usada função pd.pivot_table para agregar valores dos usuários em uma linha, com os nomes das músicas nas colunas e as notas como sendo os valores
df_ratings = pd.pivot_table(df_user_ratings2, values="rating", index="user_id", columns="name")
df_ratings.head()     # a função 'pivotada' fpo chamada de df_ratings

name      27  5:3666  A Girl Like You  ...  title track  why are you here  Ô Bebê
user_id                                ...                                       
1        1.0     NaN              1.0  ...          3.0               2.0     1.0
2        2.0     NaN              1.0  ...          3.0               2.0     2.0
3        3.0     1.0              2.0  ...          1.0               2.0     3.0
4        NaN     NaN              3.0  ...          1.0               1.0     NaN
5        NaN     2.0              3.0  ...          3.0               NaN     3.0

[5 rows x 228 columns]

# .Montar três cenários de recomendações:

## 1. Cenário 01: montar um mini sistema de recomendação com os requisitos abaixo:

### Preencher os valores faltantes com zero

In [ ]:
df_ratings.fillna(0.0, inplace=True) #preenche os valores NaN pelo valor zero
df_ratings.head()

name      27  5:3666  A Girl Like You  ...  title track  why are you here  Ô Bebê
user_id                                ...                                       
1        1.0     0.0              1.0  ...          3.0               2.0     1.0
2        2.0     0.0              1.0  ...          3.0               2.0     2.0
3        3.0     1.0              2.0  ...          1.0               2.0     3.0
4        0.0     0.0              3.0  ...          1.0               1.0     0.0
5        0.0     2.0              3.0  ...          3.0               0.0     3.0

[5 rows x 228 columns]

### Normalização

* **Garantir que a média dos dados é zero**: para isso, calculamos a média de todas as avaliações de um usuário e subtraímos a mesma de cada uma das avaliações feitas pelo usuário, ou seja, $val = x_{u, i} - \overline{x_{u}}, \; \forall \; u \in U, \; i \in I$ onde `U` é o conjunto de todos os usuários e `I` é o conjunto de todas as avaliações, $x_{u, i}$ é a avaliação que um usuário deu para um filme, $\overline{x_{u}}$ é a média das avaliações do usuário `u`. 
* **Fazer o intervalo de dados ficar entre [-1, 1]**: dividir o resultado da conta do passo 1 pelo intervalo de avaliação de cada usuário, ou seja, se a nota máxima dada por um usuário foi 5 e a mínima 1, o intervalo é igual a 4. Esse passo ajuda a garantir que todos os dados estejam na mesma escala. 

Esta função foi chamada de `adjust_rating()` e ela foi aplicada a todas as linhas do dataframe `df_ratings`, gerando o `df_ratings_std`

In [ ]:
def adjust_rating(row):
    return (row - row.mean())/(row.max()-row.min())
df_ratings1_std = df_ratings.apply(adjust_rating)
df_ratings1_std.head()       # a esta função ajustada é dada o nome de df_ratings1_std

name           27    5:3666  ...  why are you here    Ô Bebê
user_id                      ...                            
1       -0.253333 -0.593333  ...          0.053333 -0.226667
2        0.080000 -0.593333  ...          0.053333  0.106667
3        0.413333 -0.260000  ...          0.053333  0.440000
4       -0.586667 -0.593333  ...         -0.280000 -0.560000
5       -0.586667  0.073333  ...         -0.613333  0.440000

[5 rows x 228 columns]

### Foi utilizada a distância eucliana para medir similaridade (função `euclidian_distances()` do Scikit Learn).

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances

similaridade_1 = euclidean_distances(df_ratings1_std.T)    #similaridade do cenário 1 pelo médoto da distância euclidiana
print(similaridade_1)



[[0.         3.21420458 4.10852772 ... 3.79151099 3.61601377 3.88272527]
 [3.21420458 0.         3.81488313 ... 3.88730126 3.84158532 4.50308536]
 [4.10852772 3.81488313 0.         ... 3.59907395 3.39803865 4.61013377]
 ...
 [3.79151099 3.88730126 3.59907395 ... 0.         3.61509182 4.45346307]
 [3.61601377 3.84158532 3.39803865 ... 3.61509182 0.         4.03760105]
 [3.88272527 4.50308536 4.61013377 ... 4.45346307 4.03760105 0.        ]]


In [ ]:
# similaridade do cenário 1 dentro do dataframe, comparando as diversas músicas
df_similaridade_1 = pd.DataFrame(similaridade_1, index=df_ratings1_std.columns, columns=df_ratings1_std.columns)
df_similaridade_1.head()

name                            27    5:3666  ...  why are you here    Ô Bebê
name                                          ...                            
27                        0.000000  3.214205  ...          3.616014  3.882725
5:3666                    3.214205  0.000000  ...          3.841585  4.503085
A Girl Like You           4.108528  3.814883  ...          3.398039  4.610134
A Little More             3.765634  4.043101  ...          4.074037  4.152911
A Message From The Count  3.322984  3.840139  ...          3.374743  3.824192

[5 rows x 228 columns]

### Retornando as top 5 recomendações de músicas, ordenadas da música mais similar para a menos similar.

In [ ]:

# faz o ajuste de similaridade e ordena de forma decrescente
def get_recommendations_decrescente(df_similaridade_1, music, rating):
    similar_score = df_similaridade_1[music]*(rating)
    similar_score = similar_score.sort_values(ascending=False)
    return similar_score
# faz o ajuste de similaridade e ordena de forma crescente
def get_recommendations_crescente(df_similaridade_1, music, rating):
    similar_score = df_similaridade_1[music]*(rating)
    similar_score = similar_score.sort_values(ascending=True)
    return similar_score

music = "Alpha Omega"
music = input("Digite o nome da música: ")
crescente = get_recommendations_crescente(df_similaridade_1, music, 3)
decrescente = get_recommendations_decrescente(df_similaridade_1, music, 3)
print("\nTOP 5 Músicas mais parecidas com a música " + music + ":\n\n", crescente[1:6])
print("\n------------------------------------------------------\n")
print("TOP 5 Músicas menos parecidas com a música " + music + ":\n\n",decrescente[0:5])

Digite o nome da música: Alpha Omega

TOP 5 Músicas mais parecidas com a música Alpha Omega:

 name
nothing inside (feat. iann dior)    9.300538
How Does It Feel?                   9.461501
Voltei Pra Vaquejada                9.601042
concert for aliens                  9.617692
Warning Shot                        9.663333
Name: Alpha Omega, dtype: float64

------------------------------------------------------

TOP 5 Músicas menos parecidas com a música Alpha Omega:

 name
Monte Carlo                       13.885964
Glass House (feat. Naomi Wild)    13.729530
Se Namorar Fosse Bom - Ao Vivo    13.605881
Casualty                          13.586022
WWIII                             13.464026
Name: Alpha Omega, dtype: float64


## Cenário 02

### Preencher os valores faltantes com nota máxima

In [ ]:
df_ratings = pd.pivot_table(df_user_ratings2, values="rating", index="user_id", columns="name")
df_ratings.fillna(3.0, inplace=True) #preenche os valores NaN pelo valor três
df_ratings.head()

name      27  5:3666  A Girl Like You  ...  title track  why are you here  Ô Bebê
user_id                                ...                                       
1        1.0     3.0              1.0  ...          3.0               2.0     1.0
2        2.0     3.0              1.0  ...          3.0               2.0     2.0
3        3.0     1.0              2.0  ...          1.0               2.0     3.0
4        3.0     3.0              3.0  ...          1.0               1.0     3.0
5        3.0     2.0              3.0  ...          3.0               3.0     3.0

[5 rows x 228 columns]

### Normalização

* **Garantir que a média dos dados é zero**: para isso, calculamos a média de todas as avaliações de um usuário e subtraímos a mesma de cada uma das avaliações feitas pelo usuário, ou seja, $val = x_{u, i} - \overline{x_{u}}, \; \forall \; u \in U, \; i \in I$ onde `U` é o conjunto de todos os usuários e `I` é o conjunto de todas as avaliações, $x_{u, i}$ é a avaliação que um usuário deu para um filme, $\overline{x_{u}}$ é a média das avaliações do usuário `u`. 
* **Fazer o intervalo de dados ficar entre [-1, 1]**: dividir o resultado da conta do passo 1 pelo intervalo de avaliação de cada usuário, ou seja, se a nota máxima dada por um usuário foi 5 e a mínima 1, o intervalo é igual a 4. Esse passo ajuda a garantir que todos os dados estejam na mesma escala. 

Esta função foi chamada de `adjust_rating()` e ela foi aplicada a todas as linhas do dataframe `df_ratings`, gerando o `df_ratings_std`

In [ ]:
def adjust_rating(row):
    return (row - row.mean())/(row.max()-row.min())
df_ratings2_std = df_ratings.apply(adjust_rating)      # a esta função ajustada é dada o nome de df_ratings2_std
df_ratings2_std.head()     

name           27    5:3666  ...  why are you here    Ô Bebê
user_id                      ...                            
1       -0.253333 -0.593333  ...          0.053333 -0.226667
2        0.080000 -0.593333  ...          0.053333  0.106667
3        0.413333 -0.260000  ...          0.053333  0.440000
4       -0.586667 -0.593333  ...         -0.280000 -0.560000
5       -0.586667  0.073333  ...         -0.613333  0.440000

[5 rows x 228 columns]

### Foi utilizada a distância eucliana para medir similaridade (função `euclidian_distances()` do Scikit Learn).

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances

similaridade_2 = euclidean_distances(df_ratings2_std.T)      #similaridade do cenário 2 pelo médoto da distância euclidiana
print(similaridade_2)

[[0.         3.21420458 4.10852772 ... 3.79151099 3.61601377 3.88272527]
 [3.21420458 0.         3.81488313 ... 3.88730126 3.84158532 4.50308536]
 [4.10852772 3.81488313 0.         ... 3.59907395 3.39803865 4.61013377]
 ...
 [3.79151099 3.88730126 3.59907395 ... 0.         3.61509182 4.45346307]
 [3.61601377 3.84158532 3.39803865 ... 3.61509182 0.         4.03760105]
 [3.88272527 4.50308536 4.61013377 ... 4.45346307 4.03760105 0.        ]]


In [ ]:
# similaridade do cenário 1 dentro do dataframe, comparando as diversas músicas
df_similaridade_2 = pd.DataFrame(similaridade_2, index=df_ratings2_std.columns, columns=df_ratings2_std.columns)
df_similaridade_2.head()

name                            27    5:3666  ...  why are you here    Ô Bebê
name                                          ...                            
27                        0.000000  3.214205  ...          3.616014  3.882725
5:3666                    3.214205  0.000000  ...          3.841585  4.503085
A Girl Like You           4.108528  3.814883  ...          3.398039  4.610134
A Little More             3.765634  4.043101  ...          4.074037  4.152911
A Message From The Count  3.322984  3.840139  ...          3.374743  3.824192

[5 rows x 228 columns]

### Retornando as top 5 recomendações de músicas, ordenadas da música mais similar para a menos similar.

In [ ]:
# faz o ajuste de similaridade e ordena de forma decrescente
def get_recommendations_decrescente(df_similaridade_2, music, rating):
    similar_score = df_similaridade_2[music]*(rating)
    similar_score = similar_score.sort_values(ascending=False)
    return similar_score
# faz o ajuste de similaridade e ordena de forma crescente
def get_recommendations_crescente(df_similaridade_2, music, rating):
    similar_score = df_similaridade_2[music]*(rating)
    similar_score = similar_score.sort_values(ascending=True)
    return similar_score

music = "Alpha Omega"
music = input("Digite o nome da música: ")
crescente = get_recommendations_crescente(df_similaridade_2, music, 3)
decrescente = get_recommendations_decrescente(df_similaridade_2, music, 3)
print("\nTOP 5 Músicas mais parecidas com a música " + music + ":\n\n", crescente[1:6])
print("\n------------------------------------------------------\n")
print("TOP 5 Músicas menos parecidas com a música " + music + ":\n\n",decrescente[0:5])

Digite o nome da música: Alpha Omega

TOP 5 Músicas mais parecidas com a música Alpha Omega:

 name
nothing inside (feat. iann dior)    9.300538
How Does It Feel?                   9.461501
Voltei Pra Vaquejada                9.601042
concert for aliens                  9.617692
Warning Shot                        9.663333
Name: Alpha Omega, dtype: float64

------------------------------------------------------

TOP 5 Músicas menos parecidas com a música Alpha Omega:

 name
Monte Carlo                       13.885964
Glass House (feat. Naomi Wild)    13.729530
Se Namorar Fosse Bom - Ao Vivo    13.605881
Casualty                          13.586022
WWIII                             13.464026
Name: Alpha Omega, dtype: float64


## Cenário 03

### Preencher os valores faltantes com zero

In [ ]:
df_ratings = pd.pivot_table(df_user_ratings2, values="rating", index="user_id", columns="name")
df_ratings.fillna(0.0, inplace=True)   #preenche os valores NaN pelo valor zero
df_ratings.head()

name      27  5:3666  A Girl Like You  ...  title track  why are you here  Ô Bebê
user_id                                ...                                       
1        1.0     0.0              1.0  ...          3.0               2.0     1.0
2        2.0     0.0              1.0  ...          3.0               2.0     2.0
3        3.0     1.0              2.0  ...          1.0               2.0     3.0
4        0.0     0.0              3.0  ...          1.0               1.0     0.0
5        0.0     2.0              3.0  ...          3.0               0.0     3.0

[5 rows x 228 columns]

### Normalização com a mediana

In [ ]:
import statistics
def adjust_rating(row):
    return (row - row.median())/(row.max()-row.min())  #usando a mediana
df_ratings3_std = df_ratings.apply(adjust_rating)
df_ratings3_std.head()

name           27    5:3666  ...  why are you here    Ô Bebê
user_id                      ...                            
1       -0.333333 -0.666667  ...          0.000000 -0.333333
2        0.000000 -0.666667  ...          0.000000  0.000000
3        0.333333 -0.333333  ...          0.000000  0.333333
4       -0.666667 -0.666667  ...         -0.333333 -0.666667
5       -0.666667  0.000000  ...         -0.666667  0.333333

[5 rows x 228 columns]

### Utilizando a similaridade do Cosseno

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similaridade_3 = cosine_similarity(df_ratings3_std.T)    # Similaridade do cosseno
print(similaridade_3)

[[ 1.          0.40765158  0.14002801 ...  0.1514384   0.20299949
   0.06865438]
 [ 0.40765158  1.          0.25152038 ...  0.11912753  0.10757898
  -0.24558651]
 [ 0.14002801  0.25152038  1.         ...  0.23326179  0.35247761
  -0.11536243]
 ...
 [ 0.1514384   0.11912753  0.23326179 ...  1.          0.19982246
  -0.25680366]
 [ 0.20299949  0.10757898  0.35247761 ...  0.19982246  1.
  -0.07247138]
 [ 0.06865438 -0.24558651 -0.11536243 ... -0.25680366 -0.07247138
   1.        ]]


In [ ]:
# similaridade do cenário 1 dentro do dataframe, comparando as diversas músicas
df_similaridade_3 = pd.DataFrame(similaridade_3, index=df_ratings3_std.columns, columns=df_ratings3_std.columns)
df_similaridade_3.head()

name                            27    5:3666  ...  why are you here    Ô Bebê
name                                          ...                            
27                        1.000000  0.407652  ...          0.202999  0.068654
5:3666                    0.407652  1.000000  ...          0.107579 -0.245587
A Girl Like You           0.140028  0.251520  ...          0.352478 -0.115362
A Little More             0.209358  0.104014  ...          0.022100  0.044845
A Message From The Count  0.331308  0.118513  ...          0.279782  0.042580

[5 rows x 228 columns]

### Retornando as top 5 recomendações de músicas, ordenadas da música mais similar para a menos similar.

In [ ]:
# faz o ajuste de similaridade e ordena de forma decrescente
def get_recommendations_decrescente(df_similaridade_3, music, rating):
    similar_score = df_similaridade_3[music]*(rating)
    similar_score = similar_score.sort_values(ascending=False)
    return similar_score
# faz o ajuste de similaridade e ordena de forma crescente
def get_recommendations_crescente(df_similaridade_3, music, rating):
    similar_score = df_similaridade_3[music]*(rating)
    similar_score = similar_score.sort_values(ascending=True)
    return similar_score

music = "Alpha Omega"
music = input("Digite o nome da música: ")
crescente = get_recommendations_crescente(df_similaridade_3, music, 3)
decrescente = get_recommendations_decrescente(df_similaridade_3, music, 3)
print("\nTOP 5 Músicas mais parecidas com a música " + music + ":\n\n", crescente[0:5])
print("\n------------------------------------------------------\n")
print("TOP 5 Músicas menos parecidas com a música " + music + ":\n\n",decrescente[1:6])



Digite o nome da música: Alpha Omega

TOP 5 Músicas mais parecidas com a música Alpha Omega:

 name
Se Namorar Fosse Bom - Ao Vivo   -0.662394
Só Falta Você Aceitar            -0.589855
Vaqueiro da Zona Rural           -0.570088
Agora Eu Pego Mesmo              -0.565396
Sexta-Feira - Ao Vivo            -0.531688
Name: Alpha Omega, dtype: float64

------------------------------------------------------

TOP 5 Músicas menos parecidas com a música Alpha Omega:

 name
Warning Shot                        1.296228
nothing inside (feat. iann dior)    1.272221
Safe                                1.174303
Truck Norris Interlude              1.168676
concert for aliens                  1.128763
Name: Alpha Omega, dtype: float64
